/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ki.sbam.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Difficulty service. Represents a row in the &quot;sbam_Difficulty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ki.sbam.model.impl.DifficultyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ki.sbam.model.impl.DifficultyImpl}.
 * </p>
 *
 * @author Alexander Mueller, Simon Bastian
 * @see Difficulty
 * @see de.ki.sbam.model.impl.DifficultyImpl
 * @see de.ki.sbam.model.impl.DifficultyModelImpl
 * @generated
 */
@ProviderType
public interface DifficultyModel extends BaseModel<Difficulty> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a difficulty model instance should use the {@link Difficulty} interface instead.
	 */

	/**
	 * Returns the primary key of this difficulty.
	 *
	 * @return the primary key of this difficulty
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this difficulty.
	 *
	 * @param primaryKey the primary key of this difficulty
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the guaranteed of this difficulty.
	 *
	 * @return the guaranteed of this difficulty
	 */
	public boolean getGuaranteed();

	/**
	 * Returns <code>true</code> if this difficulty is guaranteed.
	 *
	 * @return <code>true</code> if this difficulty is guaranteed; <code>false</code> otherwise
	 */
	public boolean isGuaranteed();

	/**
	 * Sets whether this difficulty is guaranteed.
	 *
	 * @param guaranteed the guaranteed of this difficulty
	 */
	public void setGuaranteed(boolean guaranteed);

	/**
	 * Returns the score of this difficulty.
	 *
	 * @return the score of this difficulty
	 */
	public long getScore();

	/**
	 * Sets the score of this difficulty.
	 *
	 * @param score the score of this difficulty
	 */
	public void setScore(long score);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.ki.sbam.model.Difficulty difficulty);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.ki.sbam.model.Difficulty> toCacheModel();

	@Override
	public de.ki.sbam.model.Difficulty toEscapedModel();

	@Override
	public de.ki.sbam.model.Difficulty toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}