/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ki.sbam.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Question service. Represents a row in the &quot;sbam_Question&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ki.sbam.model.impl.QuestionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ki.sbam.model.impl.QuestionImpl}.
 * </p>
 *
 * @author Alexander Mueller
 * @see Question
 * @see de.ki.sbam.model.impl.QuestionImpl
 * @see de.ki.sbam.model.impl.QuestionModelImpl
 * @generated
 */
@ProviderType
public interface QuestionModel extends BaseModel<Question>, GroupedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a question model instance should use the {@link Question} interface instead.
	 */

	/**
	 * Returns the primary key of this question.
	 *
	 * @return the primary key of this question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this question.
	 *
	 * @param primaryKey the primary key of this question
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the question ID of this question.
	 *
	 * @return the question ID of this question
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this question.
	 *
	 * @param questionId the question ID of this question
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the group ID of this question.
	 *
	 * @return the group ID of this question
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this question.
	 *
	 * @param groupId the group ID of this question
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this question.
	 *
	 * @return the company ID of this question
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this question.
	 *
	 * @param companyId the company ID of this question
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this question.
	 *
	 * @return the user ID of this question
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this question.
	 *
	 * @param userId the user ID of this question
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this question.
	 *
	 * @return the user uuid of this question
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this question.
	 *
	 * @param userUuid the user uuid of this question
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this question.
	 *
	 * @return the user name of this question
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this question.
	 *
	 * @param userName the user name of this question
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this question.
	 *
	 * @return the create date of this question
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this question.
	 *
	 * @param createDate the create date of this question
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this question.
	 *
	 * @return the modified date of this question
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this question.
	 *
	 * @param modifiedDate the modified date of this question
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the question content of this question.
	 *
	 * @return the question content of this question
	 */
	@AutoEscape
	public String getQuestionContent();

	/**
	 * Sets the question content of this question.
	 *
	 * @param questionContent the question content of this question
	 */
	public void setQuestionContent(String questionContent);

	/**
	 * Returns the answer a of this question.
	 *
	 * @return the answer a of this question
	 */
	@AutoEscape
	public String getAnswerA();

	/**
	 * Sets the answer a of this question.
	 *
	 * @param answerA the answer a of this question
	 */
	public void setAnswerA(String answerA);

	/**
	 * Returns the answer b of this question.
	 *
	 * @return the answer b of this question
	 */
	@AutoEscape
	public String getAnswerB();

	/**
	 * Sets the answer b of this question.
	 *
	 * @param answerB the answer b of this question
	 */
	public void setAnswerB(String answerB);

	/**
	 * Returns the answer c of this question.
	 *
	 * @return the answer c of this question
	 */
	@AutoEscape
	public String getAnswerC();

	/**
	 * Sets the answer c of this question.
	 *
	 * @param answerC the answer c of this question
	 */
	public void setAnswerC(String answerC);

	/**
	 * Returns the answer d of this question.
	 *
	 * @return the answer d of this question
	 */
	@AutoEscape
	public String getAnswerD();

	/**
	 * Sets the answer d of this question.
	 *
	 * @param answerD the answer d of this question
	 */
	public void setAnswerD(String answerD);

	/**
	 * Returns the category id_fk of this question.
	 *
	 * @return the category id_fk of this question
	 */
	public long getCategoryId_fk();

	/**
	 * Sets the category id_fk of this question.
	 *
	 * @param categoryId_fk the category id_fk of this question
	 */
	public void setCategoryId_fk(long categoryId_fk);

	/**
	 * Returns the category of this question.
	 *
	 * @return the category of this question
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this question.
	 *
	 * @param category the category of this question
	 */
	public void setCategory(String category);

	/**
	 * Returns the difficulty of this question.
	 *
	 * @return the difficulty of this question
	 */
	public int getDifficulty();

	/**
	 * Sets the difficulty of this question.
	 *
	 * @param difficulty the difficulty of this question
	 */
	public void setDifficulty(int difficulty);

	/**
	 * Returns the right answer of this question.
	 *
	 * @return the right answer of this question
	 */
	@AutoEscape
	public String getRightAnswer();

	/**
	 * Sets the right answer of this question.
	 *
	 * @param rightAnswer the right answer of this question
	 */
	public void setRightAnswer(String rightAnswer);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.ki.sbam.model.Question question);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.ki.sbam.model.Question> toCacheModel();

	@Override
	public de.ki.sbam.model.Question toEscapedModel();

	@Override
	public de.ki.sbam.model.Question toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}