/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ki.sbam.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UserQuestion service. Represents a row in the &quot;sbam_UserQuestion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ki.sbam.model.impl.UserQuestionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ki.sbam.model.impl.UserQuestionImpl}.
 * </p>
 *
 * @author Alexander Mueller, Simon Bastian
 * @see UserQuestion
 * @see de.ki.sbam.model.impl.UserQuestionImpl
 * @see de.ki.sbam.model.impl.UserQuestionModelImpl
 * @generated
 */
@ProviderType
public interface UserQuestionModel extends BaseModel<UserQuestion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user question model instance should use the {@link UserQuestion} interface instead.
	 */

	/**
	 * Returns the primary key of this user question.
	 *
	 * @return the primary key of this user question
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user question.
	 *
	 * @param primaryKey the primary key of this user question
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user question.
	 *
	 * @return the user ID of this user question
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user question.
	 *
	 * @param userId the user ID of this user question
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user question.
	 *
	 * @return the user uuid of this user question
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user question.
	 *
	 * @param userUuid the user uuid of this user question
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user question.
	 *
	 * @return the user name of this user question
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this user question.
	 *
	 * @param userName the user name of this user question
	 */
	public void setUserName(String userName);

	/**
	 * Returns the question ID of this user question.
	 *
	 * @return the question ID of this user question
	 */
	public long getQuestionId();

	/**
	 * Sets the question ID of this user question.
	 *
	 * @param questionId the question ID of this user question
	 */
	public void setQuestionId(long questionId);

	/**
	 * Returns the question of this user question.
	 *
	 * @return the question of this user question
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this user question.
	 *
	 * @param question the question of this user question
	 */
	public void setQuestion(String question);

	/**
	 * Returns the answer a of this user question.
	 *
	 * @return the answer a of this user question
	 */
	@AutoEscape
	public String getAnswerA();

	/**
	 * Sets the answer a of this user question.
	 *
	 * @param answerA the answer a of this user question
	 */
	public void setAnswerA(String answerA);

	/**
	 * Returns the answer b of this user question.
	 *
	 * @return the answer b of this user question
	 */
	@AutoEscape
	public String getAnswerB();

	/**
	 * Sets the answer b of this user question.
	 *
	 * @param answerB the answer b of this user question
	 */
	public void setAnswerB(String answerB);

	/**
	 * Returns the answer c of this user question.
	 *
	 * @return the answer c of this user question
	 */
	@AutoEscape
	public String getAnswerC();

	/**
	 * Sets the answer c of this user question.
	 *
	 * @param answerC the answer c of this user question
	 */
	public void setAnswerC(String answerC);

	/**
	 * Returns the answer d of this user question.
	 *
	 * @return the answer d of this user question
	 */
	@AutoEscape
	public String getAnswerD();

	/**
	 * Sets the answer d of this user question.
	 *
	 * @param answerD the answer d of this user question
	 */
	public void setAnswerD(String answerD);

	/**
	 * Returns the category of this user question.
	 *
	 * @return the category of this user question
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this user question.
	 *
	 * @param category the category of this user question
	 */
	public void setCategory(String category);

	/**
	 * Returns the difficulty of this user question.
	 *
	 * @return the difficulty of this user question
	 */
	public int getDifficulty();

	/**
	 * Sets the difficulty of this user question.
	 *
	 * @param difficulty the difficulty of this user question
	 */
	public void setDifficulty(int difficulty);

	/**
	 * Returns the right answer of this user question.
	 *
	 * @return the right answer of this user question
	 */
	@AutoEscape
	public String getRightAnswer();

	/**
	 * Sets the right answer of this user question.
	 *
	 * @param rightAnswer the right answer of this user question
	 */
	public void setRightAnswer(String rightAnswer);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.ki.sbam.model.UserQuestion userQuestion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.ki.sbam.model.UserQuestion> toCacheModel();

	@Override
	public de.ki.sbam.model.UserQuestion toEscapedModel();

	@Override
	public de.ki.sbam.model.UserQuestion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}