/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.ki.sbam.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the UserStatistics service. Represents a row in the &quot;sbam_UserStatistics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.ki.sbam.model.impl.UserStatisticsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.ki.sbam.model.impl.UserStatisticsImpl}.
 * </p>
 *
 * @author Alexander Mueller
 * @see UserStatistics
 * @see de.ki.sbam.model.impl.UserStatisticsImpl
 * @see de.ki.sbam.model.impl.UserStatisticsModelImpl
 * @generated
 */
@ProviderType
public interface UserStatisticsModel extends BaseModel<UserStatistics> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user statistics model instance should use the {@link UserStatistics} interface instead.
	 */

	/**
	 * Returns the primary key of this user statistics.
	 *
	 * @return the primary key of this user statistics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user statistics.
	 *
	 * @param primaryKey the primary key of this user statistics
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this user statistics.
	 *
	 * @return the user ID of this user statistics
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user statistics.
	 *
	 * @param userId the user ID of this user statistics
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user statistics.
	 *
	 * @return the user uuid of this user statistics
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user statistics.
	 *
	 * @param userUuid the user uuid of this user statistics
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the games won of this user statistics.
	 *
	 * @return the games won of this user statistics
	 */
	public long getGamesWon();

	/**
	 * Sets the games won of this user statistics.
	 *
	 * @param gamesWon the games won of this user statistics
	 */
	public void setGamesWon(long gamesWon);

	/**
	 * Returns the games lost of this user statistics.
	 *
	 * @return the games lost of this user statistics
	 */
	public long getGamesLost();

	/**
	 * Sets the games lost of this user statistics.
	 *
	 * @param gamesLost the games lost of this user statistics
	 */
	public void setGamesLost(long gamesLost);

	/**
	 * Returns the right answers of this user statistics.
	 *
	 * @return the right answers of this user statistics
	 */
	public long getRightAnswers();

	/**
	 * Sets the right answers of this user statistics.
	 *
	 * @param rightAnswers the right answers of this user statistics
	 */
	public void setRightAnswers(long rightAnswers);

	/**
	 * Returns the wrong answers of this user statistics.
	 *
	 * @return the wrong answers of this user statistics
	 */
	public long getWrongAnswers();

	/**
	 * Sets the wrong answers of this user statistics.
	 *
	 * @param wrongAnswers the wrong answers of this user statistics
	 */
	public void setWrongAnswers(long wrongAnswers);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(de.ki.sbam.model.UserStatistics userStatistics);

	@Override
	public int hashCode();

	@Override
	public CacheModel<de.ki.sbam.model.UserStatistics> toCacheModel();

	@Override
	public de.ki.sbam.model.UserStatistics toEscapedModel();

	@Override
	public de.ki.sbam.model.UserStatistics toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}